### ISSUE TITLE
"Uploads should be pausable and resumable." They already are on Chromium-based browsers

### ISSUE THREAD

**Issue by guest271314** [tus/ietf-hackathon#3]
- [Streaming requests with the fetch API](https://developer.chrome.com/articles/fetch-streaming-requests/)
- [Half duplex stream](https://plnkr.co/edit/2PQK21kZTZvZ2oVi)

**Comment by Murderlon** [comment]
Thanks for the issue. We are aware of this. However, it's important to note that streaming an upload is not the same as a resumable upload. If your the streaming fetch request fails, there is no acknowledgement from the server how much it has processed and the entire upload has the start again. Furthermore, this won't work on HTTP/1.1, which is still widely in use. From my own testing I also had trouble trying to upload `FormData` as a stream, which didn't seem possible and is also a common format.

**Comment by guest271314** [comment]
> However, it's important to note that streaming an upload is not the same as a resumable upload.

The client knows how many bytes have been written. 

> If your the streaming fetch request fails, there is no acknowledgement from the server how much it has processed

That is configurable in the server. 

Node.js and Deno both support full-duplex streaming. So for each byte written to the stream the server can acknowledge the bytes written server side using the same connection, see https://gist.github.com/guest271314/d20b2a2924d0e2e0c333c01d8b8acace for the server, test for yourself from/to the browser from/to Deno Deploy [Deno](https://github.com/guest271314/native-messaging-deno/tree/fetch-duplex), [Node.js](https://github.com/guest271314/native-messaging-nodejs/tree/full-duplex). 

> Furthermore, this won't work on HTTP/1.1, which is still widely in use.

If using HTTP/2 is not your plan, what is your plan here?

> From my own testing I also had trouble trying to upload FormData as a stream, which didn't seem possible and is also a common format.

It is possible to stream a `FormData` when the data is streamed as `Uint8Array` or use `new Blob([...fd].shift()).stream()`. I don't understand the use case of _streaming_ a `FormData` object? You would have to have a specialized `FormData` stream parser for that to make sense. Even then how would you know the size of the property names cf. the values? Otherwise you're going to have to wait for the entire `FormData` request on the server side.

The requirement is already possible and in fact deployed.

**Comment by guest271314** [comment]
Oh, I see. Are you focusing on using a library https://github.com/tus/tus-js-client for this?

No library or specialized software is necessary to use resumable downloads right now using `fetch()` with `deno` or `node` JavaScript runtime executables standalone without any libraries whatsoever.

**Comment by guest271314** [comment]
Keep in mind resumable downloads are also possible on HTTP/1.1 using a `ServiceWorker`.

**Comment by Acconut** [comment]
Yes, the approach with streaming requests via the Fetch API allows you to implement pausable uploads in browsers. However, the upload can only be resumed again while the HTTP request is still open. When the underlying connection is irrecoverably destroyed, you will not be able to resume anymore.

The draft provides an method to resume the upload even if the original HTTP request is no available anymore. This allows to resume uploads even after a complete network cutoff or interruptions of a longer period.

We also want to support all recent HTTP version (>= HTTP/1.1) and not depend on specific features from a single HTTP version.

**Comment by guest271314** [comment]
> However, the upload can only be resumed again while the HTTP request is still open. When the underlying connection is irrecoverably destroyed, you will not be able to resume anymore.

I don't see how you concluded that?

If the server is sending back ackowledgment receipt of bytes received the user just resumes upload from the last offset receipt.

 If I read the draft right  it's basaed on headers. So the server has to know what to do with those headers.

I browsed through the draft. If/when adopted, we'll see.

I filed this issue because the language "Uploads should be pausable and resumable" implies they are not right now, when they are.

If I were you folks I would chime in over on https://github.com/whatwg/fetch/issues/1254. This certainly sounds like a use case for full-duplex streaming in the browser.

**Comment by Murderlon** [comment]
I think we might be focussing on the wrong thing. You are right that this draft does not create the possibility for something that was impossible before. In fact many people have implemented resumable uploads, but the key thing here is everyone does it slightly different. From briefly looking at your shared examples, you too track the bytes and and acknowledge them with headers. The RUFH draft does that too, but we are standardising the way of doing so while making it available on all versions of HTTP _and_ all client/server setups, not just fetch in the browser.

Am I correct in understanding your feedback is mostly about how we phrase this in the draft?

**Comment by guest271314** [comment]
> Am I correct in understanding your feedback is mostly about how we phrase this in the draft?

Yes.

The "should be" in

> Uploads should be pausable and resumable.

is misleading.

**Comment by guest271314** [comment]
>  From briefly looking at your shared examples, you too track the bytes and and acknowledge them with headers

No. 

What happens is the stream is full-duplex so we upload a `ReadableStream` to Deno Deploy, and read the transformed stream in the browser - using the same connection. i

In this case we are simply transforming lower case letters to upper case letters, however, we could also be encoding real-time audio and video, establishing a peer-to-peer connection with those streams by sending the uploaded stream to a subsequent client.

So in the case of full-duplex upload where the upload is pausable and resumable, everything is already built in, we are not relying on headers, we are streaming "real-time" data both ways.

E.g., in the server

```
const stream = request.body
        .pipeThrough(new TextDecoderStream())
        .pipeThrough(
          new TransformStream({
            transform(value, c) {
              c.enqueue(value.toUpperCase());
            },
            async flush() {

            },
          })
        ).pipeThrough(new TextEncoderStream());
      respondWith(new Response(
        stream, responseInit));
```

in the client, here a Native Messaging host we are using Deno's or Node.js `fetch()` to implement full-duplex streaming from the any arbitrary Web page from the browser, which no browser implements https://github.com/whatwg/fetch/issues/1254.

As you can see, when the uploaded byte is read we can send back acknowledge of that read byte immediately. So the client and server are on the same page as to what is sent and received. We are not relying on headers for that.

```
async function getMessage() {
  const header = new Uint32Array(1);
  await Deno.stdin.read(new Uint8Array(header.buffer));
  if (!writable.locked) {
    writer = writable.getWriter();
    const {
      url,
      method,
      headers = {},
      duplex = 'half'
    } = JSON.parse(decoder.decode(await readFullAsync(header[0])));
    // Returning the Promise, or using await doesn't stream
    return Promise.race([, fetch(new Request(url, {
        // Node.js logs duplex must set (to half) for upload streaming, still doesn't work using the same code
        duplex,
        method,
        headers,
        signal,
        body
      }))
      .then(({
          body: readable
        }) => readable.pipeThrough(new TextDecoderStream())
        .pipeTo(new WritableStream({
          async start() {
            now = performance.now();
            return await sendMessage(encodeMessage(`Starting read stream ${now}`));
          },
          async write(value) {
            await sendMessage(encoder.encode(value));
            gc();
          },
          async close() {
            await sendMessage(encodeMessage('Stream closed.'));
          },
          async abort(reason) {
            await sendMessage(encodeMessage({
              ABORT_REASON: reason,
              now: ((performance.now() - now) / 1000) / 60
            }));
            Deno.exit();
          }
        })))
      .then(async () => {
        ({
          writable,
          readable: body
        } = new TransformStream());
        abortable = new AbortController();
        ({
          signal
        } = abortable);
        writer = null;
        now = null;
        await sendMessage(encodeMessage('Stream reset after closing.'));
      })
      .catch(async (e) => {
        await sendMessage(encodeMessage(e.message));
      })
    ]);
  } else {
    const data = await readFullAsync(header[0]);
    const message = decoder.decode(data);
    if (message === `"ABORT_STREAM"`) {
      return abortable.abort(message);
    }
    if (message === `"CLOSE_STREAM"`) {
      await writer.close();
      return await writer.closed;
    }
    return await writer.write(data);
  }
}
```

**Comment by guest271314** [comment]
"Pause" and "Resume" and statistictics are built in to

```
const encoder = new TextEncoder();
const {readable, writable} = new TransformStream();
readable.pipeThrough(...).pipeTo(...); // Read bytes read in server
const writer = wriable.getWriter();
await writer.write(encoder.encode('a')); // Initial bytes, pause
await writer.write(encoder.encode('b')); // Resume, pause
await writer.write(encoder.encode('c')); // Resume, pause

```
